version: '3'
services:
  jupyter:
    build: .
    expose:
    - "8888"
  sut:
    image: alpine
    command: sh -c " sleep 5; wget --spider -q http://jupyter:8888 -O /dev/null"
    links:
      - jupyter
